### ISSUE TITLE
Setting up project structure

### ISSUE THREAD

**Issue by TannerGabriel** [SE2Project-BHKPTZ/backend#1]
Set up a Nodejs / Express backend project with a simple Socket.io sever and basic unit tests.

## Definition of done

- [x] Express project setup
- [x] Simple Socket.io server setup
- [x] Tests using either Jest or Mocha (including `test` script in `package.json`)

## Resources

- [Nodejs structure](https://github.com/geshan/expressjs-structure/tree/master)

**Comment by FRALEXAlexander** [comment]
I did the basic socketio and express setup
It needs testing @OlgaKupar
