### ISSUE TITLE
Add persistent storage

### ISSUE THREAD

**Issue by TannerGabriel** [SE2Project-BHKPTZ/backend#4]
To save information like user and lobby data, we should add persistent storage in the form of a database.

Current idea for the database (open for discussion):
- Database: MongoDB 
- Schema creation: Mongoose

## Definition of done

- [x] Database setup in Dockerfile (docker-compose)
- [x] Establish database connection

**Comment by FRALEXAlexander** [comment]
# Database Models

## User
* username
* uuid
* registerTimestamp
* password
* playedGames
