### ISSUE TITLE
Game lobby functionality

### ISSUE THREAD

**Issue by TannerGabriel** [SE2Project-BHKPTZ/backend#8]
Players need to be able to join a lobby and communicate with the other players. Provide the necessary SocketIO/API topics/endpoints and functionality to make this possible. Currently, we plan on a minimum of 3 and a maximum of 6 players per lobby.

Research: We should research whether we should save the lobby information in a database or if it suffices to store it in memory on the backend.

## Definition of done

- [x] Endpoints for creating and joining a lobby
- [x] The lobby should have a unique name that is used for joining the lobby
- [x] Validate if the lobby is full before letting a player join

**Comment by FRALEXAlexander** [comment]
## create Lobby:
Rest call creates a lobby and saves it to the database
Lobby model should contain:

- uuid
- lobbyid (string of 4-8 chars)
- status (created, gamerunning, done)
- name 
- player (array of user uuids)
- results (array of rounds with data for each player)

REST call returns : lobbyid

## change user:
add websocket field to model
set websocket on connect and remove on disconnect

## join Lobby:
REST call with lobbyid
set websocket room to lobbyid
